package de.westlotto.combifiles.model;

public enum DrawState {
    CLOSED,
    INIT,
    ACCEPT_DATA,
    ACCEPT_WINNING_NUMBERS,
    WINNING_NUMBERS_RECEIVED,
    WINNING_NUMBERS_CONFIRMED,
    WINNER_EVALUATION,
    WINNER_EVALUATION_CONFIRMED,
    ACCOUNTING_CALCULATION,
    ACCOUNTING_CALCULATION_CONFIRMED
}
